# Generated by Django 3.0.4 on 2020-04-04 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0007_item_todolist'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ['-priority', 'task']},
        ),
        migrations.AlterModelOptions(
            name='todolist',
            options={},
        ),
        migrations.RenameField(
            model_name='item',
            old_name='title',
            new_name='task',
        ),
    ]
