# Generated by Django 3.0.4 on 2020-04-12 02:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo_list', '0007_auto_20200411_2219'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='list',
            name='title',
        ),
        migrations.DeleteModel(
            name='ListName',
        ),
    ]
