# Generated by Django 3.0.4 on 2020-04-12 03:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_list', '0008_auto_20200412_0232'),
    ]

    operations = [
        migrations.AddField(
            model_name='list',
            name='duedate',
            field=models.DateTimeField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='list',
            name='priority',
            field=models.CharField(choices=[('High', 'High'), ('Medium', 'Medium'), ('Low', 'Low')], default='High', max_length=10),
        ),
    ]
