# Generated by Django 3.0.4 on 2020-04-04 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0008_auto_20200404_1659'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ToDoList',
            new_name='Lists',
        ),
    ]
