# Generated by Django 3.0.4 on 2020-04-04 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0009_auto_20200404_1747'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Lists',
            new_name='ToDoList',
        ),
    ]
