# Generated by Django 3.0.4 on 2020-04-04 17:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0010_auto_20200404_1749'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='todolist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='todo_list.TodoList'),
        ),
    ]
