# Generated by Django 3.0.4 on 2020-04-12 03:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('todo_list', '0011_auto_20200412_0317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='duedate',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
